deploy_locations:
    staging:
        location: "/Users/don/code/megagame/website_editor/deploy/staging"
        name: Staging
        url: "http://localhost:8000"

theme: modern
debug: true
host: 0.0.0.0

content_directory: "/Users/don/code/megagame/website_editor/content"
