deploy_locations:
    staging:
        location: "/tmp/_deploy/staging"
        name: Staging
        url: "http://localhost:8000"

theme: modern
debug: true
host: 0.0.0.0

content_directory: "./content"
